@startuml
sprite $adobe-indesign [51x50/16] {
000002EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE100000
0000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0000
008EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE600
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
2EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE1
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEEEEEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEEEEEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEEEEEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEEEEEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEEEEEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEEED888888888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEE88888888888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEB888888888888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEC8888888888888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEE888888EEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEB88888EEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEE88888EEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEE88888EEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEE88888EEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEE88888EEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEE88888EEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEE88888DEEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEE988888EEEEE8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEE8888888BCA8888AEEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEB88888888888889EEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEA8888888888888EEEEEEEEEEEEE
EEEEEEEEEEEEEE8888BEEEEEEE88888888888EEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEED988ADEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
1EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00
004EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE300
0000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0000
000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE000000
}
@enduml
