@startuml
sprite $adobe-photoshop [51x50/16] {
000002EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE100000
0000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0000
008EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE600
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
2EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE1
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEA77777777777EEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEA7777777777777EEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEA77777777777777EEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEA777777777777779EEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEA7777EEEEE777777EEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEA7777EEEEEE87777DEEEEE8777777BEEEEEEEEEE
EEEEEEEEEEEA7777EEEEEEE7777AEEEB777777777EEEEEEEEEE
EEEEEEEEEEEA7777EEEEEEE7777AEED7777777777EEEEEEEEEE
EEEEEEEEEEEA7777EEEEEEE7777BEE77777777777EEEEEEEEEE
EEEEEEEEEEEA7777EEEEEE77777EEE7777DEEEEE7EEEEEEEEEE
EEEEEEEEEEEA7777EEEEE777777EEE7777CEEEEEEEEEEEEEEEE
EEEEEEEEEEEA77777777777777AEEE777777EEEEEEEEEEEEEEE
EEEEEEEEEEEA77777777777777EEEE77777777CEEEEEEEEEEEE
EEEEEEEEEEEA7777777777778EEEEEE777777777EEEEEEEEEEE
EEEEEEEEEEEA77777777778EEEEEEEEE777777777EEEEEEEEEE
EEEEEEEEEEEA7777EEEEEEEEEEEEEEEEEE77777777EEEEEEEEE
EEEEEEEEEEEA7777EEEEEEEEEEEEEEEEEEEEA77777EEEEEEEEE
EEEEEEEEEEEA7777EEEEEEEEEEEEEEEEEEEEE97777EEEEEEEEE
EEEEEEEEEEEA7777EEEEEEEEEEEEEE77BEEEE77777EEEEEEEEE
EEEEEEEEEEEA7777EEEEEEEEEEEEEE777777777777EEEEEEEEE
EEEEEEEEEEEA7777EEEEEEEEEEEEEE77777777777EEEEEEEEEE
EEEEEEEEEEEA7777EEEEEEEEEEEEEE7777777777EEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE97777AEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
1EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00
004EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE300
0000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0000
000000EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE000000
}
@enduml
