@startuml
sprite $adobe-animate [51x50/16] {
000002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF100000
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF700
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFD555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFB555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF5555555AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF55555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA555B5555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF5555F55559FFFFFFFD5555FF555559FFFFFFFFF
FFFFFFFFFFFF5555F85555FFFFFFFE5555555555555FFFFFFFF
FFFFFFFFFFF85557FF5555FFFFFFFF55555555555555FFFFFFF
FFFFFFFFFFF5555FFF55558FFFFFFF55555555555555FFFFFFF
FFFFFFFFFFF5555FFF75555FFFFFFF55555FFFF55555EFFFFFF
FFFFFFFFFF65556FFFE5555FFFFFFF5555EFFFFC55559FFFFFF
FFFFFFFFFF5555FFFFF55556FFFFFF5555EFFFFF55557FFFFFF
FFFFFFFFFE5555FFFFF55555FFFFFF5555EFFFFF55557FFFFFF
FFFFFFFFF555555555555555DFFFFF5555EFFFFF55557FFFFFF
FFFFFFFFF5555555555555555FFFFF5555EFFFFF55557FFFFFF
FFFFFFFFE5555555555555555FFFFF5555EFFFFF55557FFFFFF
FFFFFFFF55555555555555555CFFFF5555EFFFFF55557FFFFFF
FFFFFFFF55559FFFFFFFF55555FFFF5555EFFFFF55557FFFFFF
FFFFFFFE5555FFFFFFFFF55555FFFF5555EFFFFF55557FFFFFF
FFFFFFF55555FFFFFFFFFA5555AFFF5555EFFFFF55557FFFFFF
FFFFFFF55558FFFFFFFFFF55555FFF5555EFFFFF55557FFFFFF
FFFFFFC5555FFFFFFFFFFF55555FFF5555EFFFFF55557FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF400
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000
}
@enduml
