@startuml
sprite $asciidoctor [51x51/16] {
0000000009BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB7000000000
0000000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0000000
00000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00000
0000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0000
000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB000
00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00
00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00
0BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
0BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
9BBBBBBBBBBBBBBBBBBBBBBBBB19BBBBBBBBBBBBBBBBBBBBBB4
BBBBBBBBBBBBBBBBBBBBBBBBB700BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBB0009BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBB0000BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBB10100BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBB00B002BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBB500BA00BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBB008BB007BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBA00BBB500BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBB003BBBB00BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBB00BBBBB101BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBB300BBBBBB00BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBB00ABBBBBB006BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBB800BBBBBBB700BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBB005BBBBBBBB00ABBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBB00BBBBBBBBB200BBBBBBBBBBBBBBBBB
BBBBBBBBBBBB44444440004448BBBBBB00BBBBBBBBBBBBBBBBB
BBBBBBBBBBB600000000000000BBBBBB005BBBBBBBBBBBBBBBB
BBBBBBBBBBBB33333333333336BBBBBB900BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB009BBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB300BBBBBBBBBBBBBBB
BBBBBBBBBB7777777777777BBBBBBBBBBB00BBBBBBBBBBBBBBB
BBBBBBBBB000000000000000BBBBBBBBBB003BBBBBBBBBBBBBB
BBBBBBBBB900000000000009BBBBBBBBBBA00BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB00ABBBBBBBBBBBBBBBB009BBBBBBBBBBBBB
BBBBBBBBBBBBBBB900BBBBBBBBBBBBBBBBB400BBBBBBBBBBBBB
BBBBBBBBBBBBBBB004BBBBBBBBBBBBBBBBBB00BBBBBBBBBBBBB
BBBBBBBBBBBBBBB00BBBBBBBBBBBBBBBBBBB001BBBBBBBBBBBB
BBBBBBBBBBBBBB101BBBBBBBBBBBBBBBBBBBB00BBBBBBBBBBBB
BBBBBBBBBBBBBB00BBBBBBBBBBBBBBBBBBBBB008BBBBBBBBBBB
BBBBBBBBBBBBB700BBBBBBBBBBBBBBBBBBBBB600BBBBBBBBBBB
BBBBBBBBBBBBB007BBBBBBBBBBBBBBBBBBBBBB00BBBBBBBBBBB
9BBBBBBBBBBBBA3BBBBBBBBBBBBBBBBBBBBBBB95BBBBBBBBBB3
0BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
0BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB00
00BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00
000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB000
0000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0000
00000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00000
0000000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0000000
0000000006BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB4000000000
}
@enduml
