@startuml
sprite $bootstrap [51x51/16] {
0000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0000
007BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB600
08BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB60
0BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB00000000000000000019BBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB0000000000000000000003BBBBBBBBBBBBBBB
BBBBBBBBBBBBBB00000000000000000000000BBBBBBBBBBBBBB
BBBBBBBBBBBBBB000000000000000000000000BBBBBBBBBBBBB
BBBBBBBBBBBBBB000000000000000000000000BBBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBB83000000006BBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBB10000000BBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBB0000000BBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBB0000000BBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBB0000003BBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBB000000ABBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBB0000000BBBBBBBBBBBBB
BBBBBBBBBBBBBB00000007777777720000000BBBBBBBBBBBBBB
BBBBBBBBBBBBBB0000000000000000000001BBBBBBBBBBBBBBB
BBBBBBBBBBBBBB0000000000000000000005BBBBBBBBBBBBBBB
BBBBBBBBBBBBBB000000000000000000000009BBBBBBBBBBBBB
BBBBBBBBBBBBBB0000000000000000000000009BBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBB700000000BBBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBB20000003BBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBBB0000000BBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBBB1000000BBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBBB2000000BBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBBB1000000BBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBBB0000000BBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBBBBB10000000BBBBBBBBBBB
BBBBBBBBBBBBBB0000000BBBBBBBB93000000004BBBBBBBBBBB
BBBBBBBBBBBBBB0000000000000000000000000BBBBBBBBBBBB
BBBBBBBBBBBBBB000000000000000000000000ABBBBBBBBBBBB
BBBBBBBBBBBBBB00000000000000000000000ABBBBBBBBBBBBB
BBBBBBBBBBBBBB0000000000000000000001BBBBBBBBBBBBBBB
BBBBBBBBBBBBBB00000000000000000009BBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
0BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
08BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB70
008BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB800
0000BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0000
}
@enduml
