@startuml
sprite $clio-lang [51x51/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDD37DDBBDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDD93337BBBBDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDD9338DBBBDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDD33DDBBBDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDD435DDBBDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDD33DDBBCDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDC333DBBBBDAADDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDD33339BBBBDAAADDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDD33A33BCBBDDAAADDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDD936D33BDBBCDDAAADDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDD33DD33BDDBBDDDAABDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDD33DD337DDBBDDDDAACDDDDDDDDDDDAA
AADDDDDDDDDDDDDAAAA436AA733AAAAAAAAAAADDDDDDDDDDDAA
AADDDDDDDDDDDDDAAAA33AAAA33AAAAAAAAAAABDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDC33DDBB337DDBBDDDAAADDDDDDDDDDDAA
AADDDDDDDDDDDDDDDD33ADDBBC33DDBBCDAAADDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDD33DDCBBD338DDBBAAADDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDA33DDBBDDB33DDBAAADDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDD33CDDBBDDD33BDAAADDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDAADDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}
@enduml
