@startuml
sprite $concretecms-icon [51x51/16] {
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEECEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEE000EEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEE8000EEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEE90EEEEEE0000EEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEE000EEEEE0000EEEEEEDEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEB000EEEEE0000EEEEE000EEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEC0004EEEE0000EEEEE000EEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEE0000EEEE0000EEEE7000EEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEE0000EEEE0000EEEE1000EEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEE0000EEEE0000EEEE0000EEEEEEEEEEEEEEE
EEEEEEEEE005EEEE0000EEEE0000EEEE0000EEEEEEEEEEEEEEE
EEEEEEEED000EEEE70007EEE0000EEEC0007EEEEEEEEEEEEEEE
EEEEEEEED000EEEED0002EEE0000EEE4000EEEEEEEEEEEEEEEE
EEEEEEEEE0003EEEE0000EEE3000EEE0000EEEEEEEEEEEEEEEE
EEEEEEEEE0000EEEE0000EEE7000EEE0000EEEEEEEEEEEEEEEE
EEEEEEEEEE000EEEE7000EEED004EEE0009EEEEEEEEEEEEEEEE
EEEEEEEEEE000AEEEE000EEEE00DEEE000EEEEEEEEEEEEEEEEE
EEEEEEEEEED001EEEE100EEEE40EEEE000EEEEEEEEEEEEEEEEE
EEEEEEEEEEE000EEEEE0DEEEEEEEEEE00EEEEEEEEEEEEEEEEEE
EEEEEEEEEEEE00EEEEEEEEEEEEEEEEE19EEEEEEEEEEEEEEEEEE
EEEEEEEEEEEE50DEEEE80000000002EEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEE09EE100000000000000EEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEA00000000000000001EEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEE5000000000000000000EEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEA000000000000000000EEEEEE41CEEEEEEEEEE
EEEEEEEEEEEEE000000000EEEEA4003EEEEE400004EEEEEEEEE
EEEEEEEEEEEE500000008EEEEEEEEEEEEEE000000DEEEEEEEEE
EEEEEEEEEEEE00000000EEEEEEEEEEEEEE0000001EEEEEEEEEE
EEEEEEEEEEEE0000000BEEEEEEEEEEEEE0000000EEEEEEEEEEE
EEEEEEEEEEEE0000000EEEEEEEEEEEEE0000000EEEEEEEEEEEE
EEEEEEEEEEEE00000008EEEEEEEEEEE0000000EEEEEEEEEEEEE
EEEEEEEEEEEE00000000EEEEEEEEEE0000000DEEEEEEEEEEEEE
EEEEEEEEEEEED00000000EEEEEEEE0000000CEEEEEEEEEEEEEE
EEEEEEEEEEEEE00000000007DC500000000CEEEEEEEEEEEEEEE
EEEEEEEEEEEEEE00000000000000000000CEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEE000000000000000000DEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEE0000000000000000EEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEE0000000000003EEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEC1000000CEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
0EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE0
00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE00
}
@enduml
