@startuml
sprite $concrete5 [51x51/16] {
00006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD30000
001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
01FFFD666666666666666666666666666666666666666FFFF00
0FFF9999999999999999999999999999999999999999999FFF0
7FEAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAAFF0
FFEABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAFF9
FEABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAFD
FDABBBBBBBBBBBBBBBBBBAAAA200ABBBBBBBBBBBBBBBBBBBAFF
FDBBBBBBBBBBBBBBBAAAAAAAA0008AAAABBBBBBBBBBBBBBBBFF
FDBBBBBBBBBBBBBBA34AAAAAA0005AAAAABBBBBBBBBBBBBBBFF
FCBBBBBBBBBBBBBB2007AAAA70006AAAAABBBBBBBBBBBBBBBEF
FCBBBBBBBBBBBBAA0000AAAA60006AAAA100BBBBBBBBBBBBBEF
FCBBBBBBBBBBBBBA0000AAAA60007AAAA000BBBBBBBBBBBBBEF
FBBBBBBBBBBBBBBA4000AAAA60007AAA7000BBBBBBBBBBBBBEF
FBCCBBBBBBBBBBBB80006AAA60007AAA2000BBBBBBBBBBCCCEF
FDCCCCBBBBAABBBBB0001AAA70008AAA0000BBBBBBBBBCCCCFF
FFCCCCCCBB009BBBB0000BBB80009BBB0000BBBBBBCCCCCCCFF
FFCCCCCCC6000BBBB0000BBB9000ABBB0008BBBBCCCCCCCCCFF
FFDCCCCCC9000BBBB0000BBBB000BBB5000BBCCCCCCCCCCDDFF
FFDDDDCCCC000BCCC9000BBBB000BBB0000CCCCCCCCCCDDDDFF
FFDDDDDDDC0002CCCC000CCCC000CCC0000CCCCCCDDDDDDDDFF
FFFFEEDDDDC000CCCC000BCCC000CCC000ACCDDDDDDDDEFFFFF
FEFFEEEEEED000DDDD900DDCC407DDD000DDDDDDDEEEEEFFFFF
FEFFEEEEEDDD007DDDD00DDDDD4DDDD003DDDDDDDEEEEEEFFFF
FEFEEEEEEDDD000DCCCCCCCCCCCCCCC00CDDDDDDDDEEEEEFFFF
FEFEEEEEDDDDD00CCCCCCC620015ACCCCCCDDDDDDDEEEEEEFFF
FEEEEEEEDDDDD70CCCB000000000000BCCCCDDDDDDDEEEEEFFF
FDEEEEEDDDDDDD5CC0000000000000009CCCDDDDDDDEEEEEFFF
FDEEEEEDDDDDDCC900000000000000000CCCCDDDDDDDEEEEEFF
FDEEEEEDDDDDDCA000000000000000006CCCCDDDDDDDEEEEEFF
FDEEEEDDDDDDDC000000000230000001CCCCC0000DDDEEEEEFF
FDEEEEDDDDDDC000000009BBBBBBBBCCCCC500000DDDEEEEEFF
FDEEEEDDDDDDC00000006BBBBBBBBBBCCC2000001DDDEEEEEFF
FDEEEEDDDDDDC0000000BBBBBBBBBBBCC2000000DDDDEEEEEFF
FDEEEEDDDDDDC0000000BBBBBBBBBBBC3000000DDDDDEEEEEFF
FDEEEEDDDDDDC0000000BBBBBBBBBBB5000000CDDDDDEEEEEFF
FDEEEEDDDDDDC0000000BBBBBBBBBB5000000BDDDDDDEEEEEFF
FDEEEEDDDDDDD10000000BBBBBBBB20000009CDDDDDDEEEEEFF
FDEEEEDDDDDDDC0000000008BBB200000008CDDDDDDDEEEEEFF
FDEEEEEDDDDDDC900000000000000000009CCDDDDDDDEEEEEFF
FDEEEEEDDDDDDDC700000000000000000ACCCDDDDDDEEEEEEFF
FDEEEEEDDDDDDDCCC000000000000000CCCCDDDDDDDEEEEEFFF
FDEEEEEEDDDDDDDCCC9000000000001CCCCDDDDDDDEEEEEEFFF
FCFEEEEEDDDDDDDDCCCCC9000000BCCCCCDDDDDDDDEEEEEFFFF
FEFEEEEEEDDDDDDDDCCCCCCCCCCCCCCCCDDDDDDDDEEEEEEFFFF
FFFFEEEEEEDDDDDDDDDCCCCCCCCCCCCCDDDDDDDDDEEEEEEFFFF
9FCFEEEEEEDDDDDDDDDDDCCCCCCCCDDDDDDDDDDDEEEEEEFFFF0
0FFEFEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEFFDFF0
00FFFFEEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEFFFF00
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
00001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
}
@enduml
