@startuml
sprite $django-icon [51x51/16] {
000CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB000
00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD00
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD0
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDB7327100000DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDD0000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDD400000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDD1000000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDA0000000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDD0000000DDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDC000000DDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD100000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD1000006DDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDC000000CDDDD200000DDD300000DDDDDDDDDDDDDD
DDDDDDDDDDD00000000475000000DDD300000DDDDDDDDDDDDDD
DDDDDDDDDDDB0000000000000000DDD200000DDDDDDDDDDDDDD
DDDDDDDDDDDD8000000000000000DDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDD00000000000000DDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD20000000002ADDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1000004DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD000000DDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDD0000000DDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDD30000000DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDD200000008DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDD40000CDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD72DDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD0
00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD00
000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD000
}
@enduml
