@startuml
sprite $freebsd [51x50/16] {
0BCCB0000000000000000000000000000000000000000002700
BCCCCCCC0000000000000008CCCCA400000000000000ACCCCCC
CCCCCCCCCC000000003CCCCCCCCCCCCCCA00000000CCCCCCCCC
CCCCCCCCCCCC0000CCCCCCCCCCCCCCCCCCCC2000CCCCCCCCCCC
CCCCCCCCCCC900CCCCCCCCCCCCCCCCCCCCCC90ACCCCCCCCCCCC
0CCCCCCCCC006CCCCCCCCCCCCCCCCCCCC4001CCCCCCCCCCCCC1
0CCCCCCCC00CCCCCCCCCCCCCCCCCCCCC700BCCCCCCCCCCCCCC0
0CCCCCCC00CCCCCCCCCCCCCCCCCCCCCC30BCCCCCCCCCCCCCCC0
00CCCCC00CCCCCCCCCCCCCCCCCCCCCCC80CCCCCCCCCCCCCCC00
00CCCC00CCCCCCCCCCCCCCCCCCCCCCCCC0CCCCCCCCCCCCCCC00
000CC30CCCCCCCCCCCCCCCCCCCCCCCCCC24CCCCCCCCCCCCC000
000CC0BCCCCCCCCCCCCCCCCCCCCCCCCCCC0CCCCCCCCCCCCC000
000001CCCCCCCCCCCCCCCCCCCCCCCCCCCC70CCCCCCCCCCC0000
00000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC14CCCCCCCCC70000
00007CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC05CCCCCCCC0C000
0000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC11CCCCCC09C100
0003CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC409CCC60BCC00
000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB0000009CC00
000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC80000CCC70
002CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCC0
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC6
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC9
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC6
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC1
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
006CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB0
000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
0008CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
0000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC500
0000BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC000
00000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC5000
000006CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000
000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000
0000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC500000
00000001CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB000000
000000002CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000000
0000000002CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB00000000
00000000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC8000000000
000000000000CCCCCCCCCCCCCCCCCCCCCCCCCCCC00000000000
00000000000002CCCCCCCCCCCCCCCCCCCCCCCCA000000000000
0000000000000004CCCCCCCCCCCCCCCCCCCCC00000000000000
000000000000000000CCCCCCCCCCCCCCCC40000000000000000
0000000000000000000006CCCCCCCC900000000000000000000
}
@enduml
