@startuml
sprite $greensock [102x37/16] {
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD111DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD111DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD112DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD97ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDFB7589A7DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDFAC111111112CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD67DDDDDDDD
DDDDDDDDDFA55F911511111162DDDDDDDD40000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD65558DDDDDDDDDDDDDDDDD55DDDDDDDD
DDDDDDDF6555611117DFC46F91DDDDDDD00DDD8BDDDDDDDDDDDDDDDDDDDDDDDDDDDDD555555DDDDDDDDDDDDDDDDD55DDDDDDDD
DDDDDE65555AF1119711111191DDDDDD80DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD55DDDDDDDDDDDDDDDDDDDDD55DDDDDDDD
DDDDE5555DB9E1135F71111121DDDDDD04DDDDDDD0700DC0000DDD00000DD030006DD557DDDDD65555BDD655559D55D657DDDD
DDDB555DA995811185D1111ED16DDDDD09DDDDDDD10DDD0CDD90DD0DDD07D08DDA0DD65557DDC55DA55DD55CD7DD55C55DDDDD
DDE55CC9995555E115F3111FE17DDDDD0ADD9000D10DDD0DDDD0D00DDD30D0DDDC0DDD75555D658DD55D756DDDDD5555DDDDDD
DE56FDF99655555641A1111F11EDDDDD07DDDD90D10DDD000000D0000000D0DDDC0DDDDD855D55ADD55C658DDDDD5555DDDDDD
DEADDDD98555555591C1111C19DDDDDD20DDDD90D10DDD0DDDDDD00DDDDDD0DDDC0DDDDDD55C658DD55D756DDDDD55656DDDDD
DCDDDDDB555555555E111317EDDDDDDDD07DDD90D10DDD08DDDDDD0DDDDDD0DDDC0DD559655DC55C955DD55BD7DD55D55DDDDD
DDDDDDDE5555555585111112DDDDDDDDDB000000D10DDDC00000DD100007D0DDDC0DD555559DD75555CDD755558D55DC55DDDD
DDDDDDDE5555555991111211DDDDDDDDDDDDBBDDDDDDDDDDDCDDDDDDCDDDDDDDDDDDDDDCCDDDDDDCCDDDDDDCCDDDCDDDDDDDDD
DDDDDDDDF5555799A1118411DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDEEF99A111F615DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDBA21FD71EDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDC1DDF61DDDDDDDDD9DDDDDDDDDDDDDDDDDDDDDDDCD7DDDDDDDDDDDBDDDDDDDDDDDD9DDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDE11FEFAEEDDDDDDDD99C9D98D9DD99D7CDADD9DDDBD7D98D8DDD7DBAD7DB7D7DB7DA9DDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDF11FE888DDDDDDDDD9DD8D9D8D8D8D8DCDCDD88DDCD7D97DDDDD7DAAD9DD7D7DB7DD9DDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDF13DD888DDDDDDDDDA889DAC98C89C97CDCDD88DDD98DAD8CDDD8DBDAC8D8D8DCD8DDBDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDF1FDDB55DDDDDDDDDDDDDDD98ADDD989DDDDD77DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDF1EDDE55DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDB1EDDC55DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDD11EDD86555DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDE11FDDDDEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
}
@enduml
