@startuml
sprite $html5-boilerplate [51x51/16] {
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDCCADDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD6DAAADDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD67AAAADDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDB66DAAACDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDD666BAAAADDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDD6666BAAADDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDA6666DAAABDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDD66666AAAAADDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDD666666CAAADDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD9666666DAAAADDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD66666668AAAADDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDD66666666DAAADDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDD866666666DDDDDDDDDDDDDDDDDDDDDDDD
DDDDD86666666666666666666666666666666666CDDDDDDDDDD
DDDDDDD66666666666666666666666666666666DCBBBDDDDDDD
DDDDDDDD666666666666666666666666666668DBBBBBBBDDDDD
DDDDDDDDD966666666666666666666666666CDBBBBBBBDDDDDD
DDDDDDDDDDD666666666666666666666666DCBBBBBBBDDDDDDD
DDDDDDDDDDDD6666666666666666666668DBBBBBBBCDDDDDDDD
DDDDDDDDDDDDDA666666666666666666CDBBBBBBBDDDDDDDDDD
DDDDDDDDDDDDDDD6666666666666666DCBBBBBBBDDDDDDDDDDD
DDDDDDDDDDDDDDDC66666666666666DBBBBBBBDDDDDDDDDDDDD
DDDDDDDDDDDDDDD6666666666666668BABBBBDDDDDDDDDDDDDD
DDDDDDDDDDDDDDD6666666666666666DAAABDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDD6666666666666666DAAAADDDDDDDDDDDDDDD
DDDDDDDDDDDDDD76666666666666666AAAAADDDDDDDDDDDDDDD
DDDDDDDDDDDDDD666666667666666666DAAABDDDDDDDDDDDDDD
DDDDDDDDDDDDDD6666666CCD96666666DAAAADDDDDDDDDDDDDD
DDDDDDDDDDDDD9666666DBBBCD666666BAAAADDDDDDDDDDDDDD
DDDDDDDDDDDDD66666ADBBBBBBD666666CAAACDDDDDDDDDDDDD
DDDDDDDDDDDDD6666DCBBBBBBBDDA6666DAAAADDDDDDDDDDDDD
DDDDDDDDDDDDC667DBBBBBBBDDDDDD666CAAAADDDDDDDDDDDDD
DDDDDDDDDDDD66DCBBBBBBBDDDDDDDD766BAAADDDDDDDDDDDDD
DDDDDDDDDDDD6DBBBBBBBCDDDDDDDDDDB6DAAAADDDDDDDDDDDD
DDDDDDDDDDDDDBBBBBBBDDDDDDDDDDDDDDDAAAADDDDDDDDDDDD
DDDDDDDDDDDDDDBBBBCDDDDDDDDDDDDDDDDDBAADDDDDDDDDDDD
DDDDDDDDDDDDDDDDBDDDDDDDDDDDDDDDDDDDDDBADDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
}
@enduml
