@startuml
sprite $intercom-icon [51x52/16] {
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF100FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE00FFFFFF000FFFFFA00EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0002FFFFF000FFFFF0002FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0002FFFFF000FFFFF0001FFFFFFFFFFFFFFF
FFFFFFFE2FFFFFF0002FFFFF000FFFFF0001FFFFFA0DFFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFF000FFFFF0002FFFFF000FFFFF0001FFFFF000FFFFFFF
FFFFFFFFFFFFFFF0002FFFFF000FFFFF0001FFFFFFEFFFFFFFF
FFFFFFFFFFFFFFF0002FFFFF000FFFFF0001FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0002FFFFF000FFFFF0001FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF900BFFFFF000FFFFF500DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF6FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2FFFFFFFF
FFFFFFF0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFF4000FFFFFFF
FFFFFFF00000DFFFFFFFFFFFFFFFFFFFFFFFFFC00000FFFFFFF
FFFFFFF5000000AFFFFFFFFFFFFFFFFFFFFF80000009FFFFFFF
FFFFFFFFF00000000AFFFFFFFFFFFFFFF800000000FFFFFFFFF
FFFFFFFFFF70000000000057ABA7400000000000AFFFFFFFFFF
FFFFFFFFFFFF90000000000000000000000000BFFFFFFFFFFFF
FFFFFFFFFFFFFFF500000000000000000006FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE6000000000007EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
0EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD0
00EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
}
@enduml
