@startuml
sprite $jetbrains-icon [51x51/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF1178111111D1111115FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0067000000D0000003FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF006702FFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF006701888CFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF0067000009FFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF006701FFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF60B00D7006666FFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFF00000F6000000FFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFC4CFFFFFFFFFFFFEEFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF9999DFF9999AFFFFF66FFFF77F77FFF77FFC44CFFFFFF
FFFFFE000000F000000DFFB004FFF00F001FF00F000000FFFFF
FFFFFE00FB00F00BA000FF0000FFF00F000DF00F00FF3EFFFFF
FFFFFE00EA00F00FFE00FF0000AFF00F0000F00F0008FFFFFFF
FFFFFE00000AF0010002F108D00FF00F0030000F500000FFFFF
FFFFFE00FF00F000004FF000000FF00F00F0000FFFD200FFFFF
FFFFFE00FE00D00F100F70000000F00F00FF000F02EF00FFFFF
FFFFFE000000F00FF00600EFFF00F00F00FF500D000000FFFFF
FFFFFF7777CFF77FFD7777FFFF88C99F99FFF99FFF88FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFB3333333333333333334FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFA0000000000000000001FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFA0000000000000000001FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFA0000000000000000001FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}
@enduml
