@startuml
sprite $msw [51x51/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFEDDDDDDDDDDDDDDDDDDDDDDDEFFFFFFFFFFFFF
FFFFFFFFFFF66666666666666666666666666666FFFFFFFFFFF
FFFFFFFFFF6666666666666666666666666666666FFFFFFFFFF
FFFFFFFFFB6666666666666666666666666666666FFFFFFFFFF
FFFFFFFFF66666666666666666666666666666666CFFFFFFFFF
FFFFFFFFF66666666666666666666666666666666CFFFFFFFFF
FFFFFFFFFB6666666666666666666666666666666EFFFFFFFFF
FFFFFFFFFF666666669CCCCCCCFFFFFFFFF666666FFFFFFFFFF
FFFFFFFFFFF66666666ACCCCCCCFFFFFFFF666666FFFFFFFFFF
FFFFFFFFFFFC66666666BCCCCCCCFFFFFFF666666FFFFFFFFFF
FFFFFFFFFFFCB66666666CCCCCCCCFFFFFC666666FFFFFFFFFF
FFFFFFFFFFFCCA66666666CCCCCCCCFFFF9666666FFFFFFFFFF
FFFFFFFFFFFCCC966666666CCCCCCCCFFF8666666FFFFFFFFFF
FFFFFFFFFFFCCCC866666666CCCCCCCCFF6666666FFFFFFFFFF
FFFFFFFFFFDCCCCC766666666CCCCCCCDF666666AFFFFFFFFFF
FFFFFFFFFFCCCCCCC666666667CCCCCCCD666666EFFFFFFFFFF
FFFFFFFFFFCCCCCCDF666666668CCCCCCC666666FFFFFFFFFFF
FFFFFFFFFFCCCCCCDFF666666669CCCCCC666666FFFFFFFFFFF
FFFFFFFFFFCCCCCCEFFF66666666ACCCCC666666FFFFFFFFFFF
FFFFFFFFFFCCCCCCFFFFF66666666BCCCB666666FFFFFFFFFFF
FFFFFFFFFFCCCCCCFFFFFE66666666CCC9666666FFFFFFFFFFF
FFFFFFFFFFCCCCCCFFFFFFD66666666CC8666666FFFFFFFFFFF
FFFFFFFFFFCCCCCCFFFFFFFA66666666C7666666FFFFFFFFFFF
FFFFFFFFFECCCCCCFFFFFFFF8666666666666668FFFFFFFFFFF
FFFFFFFFFDCCCCCCCCCCCCCCC76666666666666CFFFFFFFFFFF
FFFFFFFFFCCCCCCCCCCCCCCCCC6666666666666EFFFFFFFFFFF
FFFFFFFFFCCCCCCCCCCCCCCCCCC666666666666FFFFFFFFFFFF
FFFFFFFFFECCCCCCCCCCCCCCCCCC66666666666FFFFFFFFFFFF
FFFFFFFFFFCCCCCCCCCCCCCCCCCCC6666666666FFFFFFFFFFFF
FFFFFFFFFFFCCCCCCCCCCCCCCCCCCC666666666FFFFFFFFFFFF
FFFFFFFFFFFFFEEEEEEEEEEEEEEEEED6666666CFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD666667FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF967FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}
@enduml
