@startuml
sprite $presto [51x51/16] {
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF7EFFFFFFFF44FFFFFFFF966FFFFFFFFFFFFFFFFFFFFFF
FFFFF000FFFFFFF7444FFFFFFF666AFFFFFFFFFFFFFFFFFFFFF
FFFFF200FFFFFFF7444FFFFFFF666BFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF54FFFFFFFFA67FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF9CFFFFFFFF94CFFFFFFFB66FFFFFFFFFFFFFFFFF
FFFFFFFFFF0006FFFFFFD444FFFFFFF6666FFFFFFFFFFFFFFFF
FFFFFFFFFF0001FFFFFFA444FFFFFFF6666FFFFFFFFFFFFFFFF
FFFFFFFFFFC00FFFFFFFF444FFFFFFF666AFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFC9FFFFFFFFB47FFFFFFFD66CFFFFFFFFFFF
FFFFFFFFFFFFFFF8000FFFFFFE4448FFFFFF6666FFFFFFFFFFF
FFFFFFFFFFFFFFF0000FFFFFF94444FFFFFF6666EFFFFFFFFFF
FFFFFFFFFFFFFFFB000FFFFFFF444CFFFFFF6666FFFFFFFFFFF
FFFFFFFFFFFFFFFFFEFFFFFFFFF9EFFFFFFFF66FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFD44FFFFFFFF668FFFFFF
FFFFFFFFFFFFFFFFFFFFA000FFFFFFF4444FFFFFF66669FFFFF
FFFFFFFFFFFFFFFFFFFF00006FFFFF84444FFFFFF66666FFFFF
FFFFFFFFFFFFFFFFFFFF4000DFFFFFE4444FFFFFF66666FFFFF
FFFFFFFFFFFFFFFFFFFFF409FFFFFFF944FFFFFFFD666FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF5DFFFFFFFF54FFFFFFFFFFFF
FFFFFFFFFFFFFFFF66EFFFFFFC0005FFFFFF4444FFFFFFFFFFF
FFFFFFFFFFFFFFFC666FFFFFF00000FFFFFB44448FFFFFFFFFF
FFFFFFFFFFFFFFFE666FFFFFF10000FFFFFE4444BFFFFFFFFFF
FFFFFFFFFFFFFFFFDAFFFFFFFF000EFFFFFF4444FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBEFFFFFFFFFFFFFFFFF
FFFFFFFFFFF88FFFFFFFFD7FFFFFFFF0000FFFFFFFFFFFFFFFF
FFFFFFFFFF6668FFFFFFF666FFFFFF10000FFFFFFFFFFFFFFFF
FFFFFFFFFF6668FFFFFFF666FFFFFF00000FFFFFFFFFFFFFFFF
FFFFFFFFFFF66FFFFFFFFB6EFFFFFFE0000FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF37FFFFFFFFFFFFFFFFF
FFFFFFCFFFFFFFFFFCFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFF
FFFFF666FFFFFFFE666FFFFFFF666FFFFFFFFFFFFFFFFFFFFFF
FFFFF666CFFFFFFC666FFFFFFF666FFFFFFFFFFFFFFFFFFFFFF
FFFFFD66FFFFFFFF66DFFFFFFF966FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
}
@enduml
