@startuml
sprite $rackspace-icon [51x51/16] {
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA768BBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB00000000BBBB9000009BBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB00000004BBB0000000BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB00000009B800000000BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB80000000B7000000000BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB20000000B0000000000BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB0000000000000000007BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB000000010000000000BBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB000000000000000000BBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB900000000000004ABBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB400000000000ABBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB00000000000BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB0000000000BBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB0000000009BBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBA000000000BBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB6000000008BBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB000000000BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB000000000BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB000000004BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB00000000ABBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBB700000000BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBB000000000BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBB000000000BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBB000000003BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBB000000008BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB900000000BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB200000000BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB000000000BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB000000002BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB000000007BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBB900000000BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
}
@enduml
