@startuml
sprite $scala [51x83/16] {
000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000A
0000000000000000000000000000000000000000000000000BB
000000000000000000000000000000000000000000000006BBB
000000000000000000000000000000000000000000000BBBBBB
000000000000000000000000000000000000000001BBBBBBBBB
00000000000000000000000000000000000001BBBBBBBBBBBBB
000000000000000000000000000000001ABBBBBBBBBBBBBBBBB
0000000000000000000000000007BBBBBBBBBBBBBBBBBBBBBBB
000000000000000000003ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB
00000000000015CCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
0000018CCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
6CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB4
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB40
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB200
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDFFFF0
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBDFFFFFFFF
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBDEEFFFFFFFFFF
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBCEEEEEEEFFFFFFFFFF
CCCCCCCCCCCCCCCCBBBBBBBBBBBCCDDEEEEEEEEEEFFFFFFFFFB
CCCCCCCCCCCCCCCCBBBBBCCDDDDDDDDEEEEEEEEEEFFFFFFFDBB
CCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFFDBBBB
CCCCCCCBBBCCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFDBBBBBBB
CBBBBBBBBBCCCCCCCCCCCDDDDDDDDDDEEEEEEEEECBBBBBBBBBB
05ABBBBBBBCCCCCCCCCCCDDDDDDDDDDEEEEDBBBBBBBBBBBBBBB
000000037BCCCCCCCCCCCDDDDDDDDDCBBBBBBBBBBBBBBBBBBBB
0000000000000016ACCCCDDDCBBBBBBBBBBBBBBBBBBBBBBBBBB
000000000000000025ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
00000000037CCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
0038CCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB900
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCFF00
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFF0
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBCEFFFFFFFFF
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBDEEEEFFFFFFFFFF
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBDEEEEEEEEEFFFFFFFFFC
CCCCCCCCCCCCCCCCBBBBBBBBBCDDDDDEEEEEEEEEEFFFFFFFFCB
CCCCCCCCCCCCCCCCBCCCCDDDDDDDDDDEEEEEEEEEEFFFFFFEBBB
CCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEFFFFCBBBBB
CCCBBBBBBBCCCCCCCCCCCDDDDDDDDDDEEEEEEEEEEECBBBBBBBB
BBBBBBBBBBCCCCCCCCCCCDDDDDDDDDDEEEEEEECBBBBBBBBBBBB
00016BBBBBCCCCCCCCCCCDDDDDDDDDDEECBBBBBBBBBBBBBBBBB
000000000015ACCCCCCCCDDDDDDCCBBBBBBBBBBBBBBBBBBBBBB
00000000000000000039CCBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
000000000000039BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
0000006ACCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
4BCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB6
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB60
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB000
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBB700000
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBB600000000
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBB9000000000000
CCCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBB20000000000000000
CCCCCCCCCCCCCCCCBBBBBBBBBBBB70000000000000000000000
CCCCCCCCCCCCCCCCBBBBBB40000000000000000000000000000
CCCCCCCCCCCCCCB300000000000000000000000000000000000
CCCCCCC70000000000000000000000000000000000000000000
C40000000000000000000000000000000000000000000000000
}
@enduml
