@startuml
sprite $scala [51x83/16] {
000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000A
0000000000000000000000000000000000000000000000000BB
000000000000000000000000000000000000000000000006BBB
000000000000000000000000000000000000000000000BBBBBB
000000000000000000000000000000000000000001BBBBBBBBB
00000000000000000000000000000000000001BBBBBBBBBBBBB
000000000000000000000000000000001ABBBBBBBBBBBBBBBBB
0000000000000000000000000007BBBBBBBBBBBBBBBBBBBBBBB
000000000000000000003ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB
00000000000015CBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
0000018CCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
6CCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB4
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB40
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB200
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDFFFF0
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBDFFFFFFFF
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBCEEFFFFFFFFFF
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBCEEEEEEEFFFFFFFFFF
CCCCCCCCCCCCCCCBBBBBBBBBBBBCCDEEEEEEEEEEEFFFFFFFFFB
CCCCCCCCCCCCCCCBBBBBBCCDDDDDDDEEEEEEEEEEEFFFFFFFDBB
CCCCCCCCCCCCCCCCCCCCCDDDDDDDDDEEEEEEEEEEEFFFFFDBBBB
CCCCCCCBBBCCCCCCCCCCCDDDDDDDDDEEEEEEEEEEEFFDBBBBBBB
CBBBBBBBBBCCCCCCCCCCCDDDDDDDDDEEEEEEEEEECBBBBBBBBBB
05ABBBBBBBCCCCCCCCCCCDDDDDDDDDEEEEEDBBBBBBBBBBBBBBB
000000038BCCCCCCCCCCCDDDDDDDDDCBBBBBBBBBBBBBBBBBBBB
0000000000000016ACCCCDDDCBBBBBBBBBBBBBBBBBBBBBBBBBB
000000000000000025ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
00000000037CCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
0038CCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB0
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB900
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCFF00
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEFFFFF0
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBCEFFFFFFFFF
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBDEEEEFFFFFFFFFF
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBDEEEEEEEEEFFFFFFFFFC
CCCCCCCCCCCCCCCBBBBBBBBBBCDDDDEEEEEEEEEEEFFFFFFFFCB
CCCCCCCCCCCCCCCBBCCCCDDDDDDDDDEEEEEEEEEEEFFFFFFEBBB
CCCCCCCCCCCCCCCCCCCCCDDDDDDDDDEEEEEEEEEEEFFFFCBBBBB
CCCBBBBBBBCCCCCCCCCCCDDDDDDDDDEEEEEEEEEEEECBBBBBBBB
BBBBBBBBBBCCCCCCCCCCCDDDDDDDDDEEEEEEEECBBBBBBBBBBBB
00016BBBBBCCCCCCCCCCCDDDDDDDDDEEECBBBBBBBBBBBBBBBBB
000000000015ACCCCCCCCDDDDDDCCBBBBBBBBBBBBBBBBBBBBBB
00000000000000000039CCBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
000000000000039BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
0000006ACCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
4BCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB6
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB60
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB000
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB700000
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBBBBBB600000000
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBBBBBB9000000000000
CCCCCCCCCCCCCCCBBBBBBBBBBBBBBBBBBB20000000000000000
CCCCCCCCCCCCCCCBBBBBBBBBBBBB70000000000000000000000
CCCCCCCCCCCCCCCBBBBBBB40000000000000000000000000000
CCCCCCCCCCCCCCB300000000000000000000000000000000000
CCCCCCC70000000000000000000000000000000000000000000
C40000000000000000000000000000000000000000000000000
}
@enduml
