@startuml
sprite $survicate-icon [51x51/16] {
000000000AEEE000000000DEE6000000002EEEEEE9000000000
0000001EEEEEE0000005EEEEE6000000CEEEEEEEEEEE0000000
00000EEEEEEEE00000EEEEEEE600001EEEEEEEEEEEEEEE00000
0000EEEEEEEEE0000EEEEEEEE60007EEEEEEEEEEEEEEEEE0000
000EEEEEEEEEE000EEEEEEEEE6005EEEEEEEEEEEEEEEEEEE000
00EEEEEEEEEEE00EEEEEEEEEE600EEEEEEEEEEEEEEEEEEEEE00
01EEEEEEEEEEE0BEEEEEEEEEE60EEEEEEEEEEEEEEEEEEEEEE00
0EEEEEEEEEEEE0EEEEEEEEEEE62EEEEEEEEEEEEEEEEEEEEEEE0
0EEEEEEEEEEEE8EEEEEEEEEEE6EEEEEEEEEEEEEEEEEEEEEEEE0
CEEEEEEEEEEEEEEEEEEEEEEEE6EEEEEEEEEEEEEEEEEEEEEEEEA
EEEEEEEEEEEEEEEEEEEEEEEEE6EEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEBEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEBEEEEEEEEEEEEEEEEA00000000
EEEEEEEEEEEEEEEEEEEEEEEEE3EEEEEEEEEEEEEEEEEEC000000
EEEEEEEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEE00000
1EEEEEEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEEE0000
0EEEEEEEEEEEEEEEEEEEEEEE809EEEEEEEEEEEEEEEEEEEEE000
0CEEEEEEEEEEEEEEEEEEEEEE000EEEEEEEEEEEEEEEEEEEEEE00
00EEEEEEEEEEEEEEEEEEEEE70008EEEEEEEEEEEEEEEEEEEEE60
000EEEEEEEEEEEEEEEEEEEE00000EEEEEEEEEEEEEEEEEEEEEE0
0005EEEEEEEEEEEEEEEEEE0000000EEEEEEEEEEEEEEEEEEEEE0
00002EEEEEEEEEEEEEEED000000000EEEEEEEEEEEEEEEEEEEEE
000000EEEEEEEEEEEEE6000000000007EEEEEEEEEEEEEEEEEEE
00000000DEEEEEEEE70000000000000007EEEEEEEEEEEEEEEEE
99999999999BEB40000000000000000000004BDB64444444444
EEEEEEEEEEEEEEEEEC000000000000000CEEEEEEEEE40000000
EEEEEEEEEEEEEEEEEEEB00000000000BEEEEEEEEEEEEE000000
EEEEEEEEEEEEEEEEEEEEE000000000EEEEEEEEEEEEEEEE80000
0EEEEEEEEEEEEEEEEEEEEE0000000EEEEEEEEEEEEEEEEEEA000
0EEEEEEEEEEEEEEEEEEEEEE00000EEEEEEEEEEEEEEEEEEEE200
03EEEEEEEEEEEEEEEEEEEEEA000BEEEEEEEEEEEEEEEEEEEEE00
00EEEEEEEEEEEEEEEEEEEEEE000EEEEEEEEEEEEEEEEEEEEEEE0
000EEEEEEEEEEEEEEEEEEEEEA0BEEEEEEEEEEEEEEEEEEEEEEE0
0000EEEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEEEEEE3
00000EEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEEEEEEE
0000007EEEEEEEEEEEEEEEEEE5EEEEEEEEEEEEEEEEEEEEEEEEE
000000003DEEEEEEEEEEEEEEEBEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEE7EEEEEEEEEEEEEEEEEEEEEEEEE
9EEEEEEEEEEEEEEEEEEEEEEEE7EEEEEEEEEEEEEEEEEEEEEEEE8
0EEEEEEEEEEEEEEEEEEEEEEED7EEEEEEEEEEE5EEEEEEEEEEEE0
0EEEEEEEEEEEEEEEEEEEEEEE07EEEEEEEEEEE0EEEEEEEEEEEE0
00EEEEEEEEEEEEEEEEEEEEED07EEEEEEEEEE70EEEEEEEEEEE00
00CEEEEEEEEEEEEEEEEEEEE007EEEEEEEEEE00EEEEEEEEEEB00
000EEEEEEEEEEEEEEEEEEE1007EEEEEEEEE000EEEEEEEEEE000
0000EEEEEEEEEEEEEEEEE10007EEEEEEEE0000EEEEEEEEE0000
00000AEEEEEEEEEEEEEE000007EEEEEEE00000EEEEEEE900000
0000000EEEEEEEEEEE30000007EEEEE0000000EEEEEE0000000
0000000001EEEEE80000000007EE4000000000EEE0000000000
}
@enduml
