@startuml
sprite $typescript-icon [51x51/16] {
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA777777777777777777AAAAAAA820138AAAAAAAAA
AAAAAAAAAAA000000000000000000AAAAA6000000008AAAAAAA
AAAAAAAAAAA000000000000000000AAAA300000000006AAAAAA
AAAAAAAAAAA000000000000000000AAA90000000000009AAAAA
AAAAAAAAAAA000000000000000000AAA0000005500000AAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAA00000AAAA006AAAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAA00001AAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAA00000AAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAA000000AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAA40000001AAAAAAAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAA0000000009AAAAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAAA0000000000AAAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAAAA1000000000AAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAAAAAA000000000AAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAAAAAAAA30000007AAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAAAAAAAAAA000000AAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAAAAAAAAAAA00000AAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAA00AAAAAAA00000AAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAA40000AAAAAA00000AAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAA90000004AA3000000AAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAA2000000000000009AAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAA10000000000006AAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAA800000000008AAAAAA
AAAAAAAAAAAAAAAAAA00002AAAAAAAAAAAA90000009AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}
@enduml
